version: '3'

services:

  app:
    container_name: nest-api
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 4000:4000
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  
  db:
    container_name: pg_container  
    image: postgres  
    restart: always
    ports: 
      - "5480:5432"    
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest_api

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db

networks:
  nesjs-network: